Avoid typescript error TS7017 by explicitly casting global
This avoids this specific error when using react-native-file-logger and running `tsc -noEmit`:

error TS7017: Element implicitly has an 'any' type because type 'typeof globalThis' has no index signature.